// pch.h

/*
	Problems with headers in compilation?
		Try commenting-out parts (or everything) below!
*/

#pragma once


#include "DetectBoard.h"
#include "Globals.h"

#include "ArduinoClock.h"
#include "ArduinoDevice.h"
#include "ArduinoDHT.h"
#include "ArduinoMFShield.h"
#include "ArduinoNeoPixel.h"
#include "ArrayHelpers.h"
#include "Beacon.h"
#include "BeaconManager.h"
#include "Bridge.h"
#include "BridgeManager.h"
#include "CmdInterpreter.h"
#include "CommandSet.h"
#include "ConfigProp.h"
#include "Configuration.h"
#include "Connection.h"
#include "ConnectionManager.h"
#include "cppQueue.h"
#include "DataLogger.h"
#include "DataLoggerManager.h"
#include "DateTime.h"
#include "Device.h"
#include "DeviceCodec1.h"
#include "DeviceManager.h"
#include "Dictionary.h"
#include "Displayer.h"
#include "Dynamic.h"
#include "Enumeration.h"
#include "EthernetInterface.h"
#include "FieldReplacer.h"
#include "FifoBuffer.h"
#include "Filter.h"
#include "FilterManager.h"
#include "HttpConnection.h"
#include "Int8List.h"
#include "IoTClock.h"
#include "IoTManager.h"
#include "IoTMessage.h"
#include "IoTObject.h"
#include "Log.h"
#include "LogConnection.h"
#include "MemoryFreeExt.h"
#include "MessageFilter.h"
#include "MessageFilterItem.h"
#include "NetworkInterface.h"
#include "NetworkManager.h"
#include "Part.h"
#include "PartManager.h"
#include "PersistentFile.h"
#include "PersistentFileManager.h"
#include "Register.h"
#include "Route.h"
#include "RtcClock.h"
#include "SerialConnection.h"
#include "Shield.h"
#include "ShieldManager.h"
#include "StringList.h"
#include "Table.h"
#include "TcpConnection.h"
#include "Tests.h"
#include "ThinkerShield.h"
#include "UdpConnection.h"
#include "UserPart.h"
#include "Utils.h"
#include "WiFiInterface.h"
#include "WiFiLibrary.h"


